# ============================================================
# Outputs - ส่งค่า IP และ Ansible Action Configuration
# ============================================================

output "vpc_id" {
  description = "ID ของ VPC ที่สร้างขึ้น"
  value       = aws_vpc.main.id
}

output "web_server_public_ip" {
  description = "Public IP ของ Web Server"
  value       = aws_instance.web.public_ip
}

output "web_server_private_ip" {
  description = "Private IP ของ Web Server"
  value       = aws_instance.web.private_ip
}

output "db_server_public_ip" {
  description = "Public IP ของ DB Server (ใช้ SSH เข้าไป manage)"
  value       = aws_instance.db.public_ip
}

output "db_server_private_ip" {
  description = "Private IP ของ DB Server (ให้ Web Server เชื่อมต่อ)"
  value       = aws_instance.db.private_ip
}

output "web_url" {
  description = "URL สำหรับเข้าถึง Web Application"
  value       = "http://${aws_instance.web.public_ip}"
}

output "private_key_pem" {
  description = "SSH Private Key สำหรับเข้า EC2 (sensitive)"
  value       = tls_private_key.ssh_key.private_key_openssh
  sensitive   = true
}

output "ansible_inventory_json" {
  description = "Dynamic inventory JSON generated by data.ansible_inventory"
  value       = data.ansible_inventory.myinventory.json
  sensitive   = true
}

output "ansible_playbook_path" {
  description = "Playbook file path configured in ansible.tf action"
  value       = "${path.module}/../ansible/playbook.yml"
}

output "ansible_extra_vars" {
  description = "Extra variables configured in ansible.tf action"
  value = {
    db_host     = aws_instance.db.private_ip
    db_password = var.db_password
  }
  sensitive = true
}
